title: Project

options:
  template: false
  status: true
  url: false

files:
  sortable: true
  fields:
    text:
      label: Caption
      type: markdown

pages: false

fields:
  title:
    label: Title
    type:  text

  text:
    label: Text
    type:  markdown
